swagger: "2.0"

# document metadata
info:
  version: "0.0.1"
  title: Example Service

host: api.example.com
basePath: /photo
schemes:
  - https

# Endpoints
paths:
  # example with query parameters
  /album:
    get:
      parameters:
        - name: start
          in: query
          required: false
          type: string
        - name: end
          in: query
          required: false
          type: string
  # example with path parameter
  /album/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
