swagger: "2.0"

# document metadata
info:
  version: "0.3.0"
  title: Music API

host: muzicplayz.com
basePath: /v3
schemes:
  - https

# Endpoints
paths:
  # return one or more playlists
  /playlist:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
        - name: offset
          in: query
          required: false
          type: integer
        - name: search
          in: query
          required: false
          type: string
      responses:
        200:
          description: Success
  # delete a playlist
  /playlist/{playlist-id}:
    delete:
      parameters:
        - name: playlist-id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
